apiVersion: v1
kind: ConfigMap
metadata:
  name: node-watch-config
  namespace: node-watch
  labels:
    app.kubernetes.io/name: node-watch
    app.kubernetes.io/part-of: node-watch
    app.kubernetes.io/component: telemetry
data:
  NODEWATCH_LOG_LEVEL: "INFO"
  NODEWATCH_LOG_JSON: "true"
  NODEWATCH_API_HOST: "0.0.0.0"
  NODEWATCH_API_PORT: "8080"