apiVersion: v1
kind: Service
metadata:
  name: node-watch
  namespace: node-watch
  labels:
    app.kubernetes.io/name: node-watch
    app.kubernetes.io/part-of: node-watch
    app.kubernetes.io/component: telemetry
spec:
  selector:
    app.kubernetes.io/name: node-watch
  ports:
    - name: http
      protocol: TCP
      port: 8080
      targetPort: http
  type: ClusterIP